program: rq/train_combiner.py
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  hidden_dim:
    values: [4, 8, 16, 32]
  batch_size:
    values: [512, 1024, 2048]
  epochs:
    value: 50
  preset:
    value: wiki_valid
  from_cache:
    value: true
  use_wandb:
    value: true
